import 'form_models.dart';

class FormSchemas {
  static const musalla = FormSchema(
    typeId: 'musalla',
    fields: [
      FormFieldSpec(
        id: 'mosque_name',
        labelAr: 'اسم المسجد',
        type: FieldType.text,
      ),
      FormFieldSpec(
        id: 'area',
        labelAr: 'المساحة بالمتر المربع',
        type: FieldType.number,
        min: 32,
        max: 170,
      ),
      FormFieldSpec(
        id: 'location',
        labelAr: 'المكان',
        type: FieldType.dropdown,
        options: ['محافظة', 'مدينة', 'بلدة', 'قرية'],
      ),
      FormFieldSpec(
        id: 'quality',
        labelAr: 'الجودة',
        type: FieldType.dropdown,
        options: ['اقتصادي', 'متوسطة', 'عالية'],
      ),
      FormFieldSpec(
        id: 'needs_renovation',
        labelAr: 'مسجد مهدم جزئي أو بحاجة إلى صيانة أو فرش وتأثيث',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'structural_condition',
        labelAr:
            'أعمال إنشائية (هبكل خرسانة, رقبة, أساسات, بلاطة سقف, جوائز, صب نطافة, رافعة معدنية, خزانات بيتونية تحت الأرض)',
        type: FieldType.dropdown,
        options: ['سليم', 'بحاجة إلى ترميم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'structural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'structural_condition',
        dependsOnEquals: 'بحاجة إلى ترميم',
      ),
      FormFieldSpec(
        id: 'architectural_condition',
        labelAr:
            'أعمال معمارية وديكور (بلوك, لياسة, عزل, أرضيات, أبواب, شبابيك, تلبيس الحجر, دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'architectural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'architectural_condition',
        dependsOnEquals: 'غير سليم',
      ),
      // FormFieldSpec(
      //   id: 'decor_presence',
      //   labelAr: 'أعمال الديكور (دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
      //   type: FieldType.dropdown,
      //   options: ['موجود', 'غير موجود'],
      //   dependsOn: 'needs_renovation',
      //   dependsOnEquals: true,
      // ),
      // FormFieldSpec(
      //   id: 'decor_missing_percent',
      //   labelAr: 'النسبة المئوية',
      //   type: FieldType.number,
      //   dependsOn: 'decor_presence',
      //   dependsOnEquals: 'غير موجود',
      // ),
      FormFieldSpec(
        id: 'hvac_presence',
        labelAr: 'تكييف وتدفئة ومراوح (خزان مازوت ومولدة)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_presence',
        labelAr:
            'الكهرباء والتيار الخفيف (إنارة, صوت, كاميرات إنذار حريق, قواطع)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'electric_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'renewable_presence',
        labelAr: 'الطاقة البديلة (ألواح, بطاريات ليثيوم, إنفرتر)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'renewable_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'renewable_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'minaret_condition',
        labelAr: 'المئذنة',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'minaret_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'minaret_condition',
        dependsOnEquals: 'غير سليم',
      ),
      FormFieldSpec(
        id: 'water_condition',
        labelAr:
            'العوامل المائية (موضأ, حمامات, تصريف مطري, سقاية الحديقة, خزانات مياه ومضخات)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'water_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'water_condition',
        dependsOnEquals: 'غير سليم',
      ),
    ],
  );

  static const small = FormSchema(
    typeId: 'small',
    fields: [
      FormFieldSpec(
        id: 'mosque_name',
        labelAr: 'اسم المسجد',
        type: FieldType.text,
      ),
      FormFieldSpec(
        id: 'area',
        labelAr: 'المساحة بالمتر المربع',
        type: FieldType.number,
        min: 170,
        max: 500,
      ),
      FormFieldSpec(
        id: 'sharia_institute',
        labelAr: 'معهد شرعي',
        type: FieldType.dropdown,
        options: ['0', '8', '16', '24'],
      ),
      FormFieldSpec(id: 'basement', labelAr: 'قبو', type: FieldType.boolean),
      FormFieldSpec(
        id: 'basement_area',
        labelAr: 'مساحة القبو',
        type: FieldType.number,
        min: 1,
        dependsOn: 'basement',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'imam_house',
        labelAr: 'بيت إمام',
        type: FieldType.dropdown,
        options: ['1', '2', '3'],
      ),
      FormFieldSpec(id: 'courtyard', labelAr: 'صحن', type: FieldType.boolean),
      FormFieldSpec(
        id: 'courtyard_area',
        labelAr: 'مساحة الصحن',
        type: FieldType.number,
        min: 1,
        dependsOn: 'courtyard',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'shops',
        labelAr: 'محلات تجارية',
        type: FieldType.dropdown,
        options: ['2', '3', '4'],
      ),
      FormFieldSpec(
        id: 'shops_area',
        labelAr: 'مساحة المحل الواحد',
        type: FieldType.number,
        min: 1,
        dependsOn: 'shops',
        dependsOnNotEmpty: true,
      ),
      FormFieldSpec(
        id: 'location',
        labelAr: 'المكان',
        type: FieldType.dropdown,
        options: ['محافظة', 'مدينة', 'بلدة', 'قرية'],
      ),
      FormFieldSpec(
        id: 'quality',
        labelAr: 'الجودة',
        type: FieldType.dropdown,
        options: ['اقتصادي', 'متوسطة', 'عالية'],
      ),
      FormFieldSpec(
        id: 'needs_renovation',
        labelAr: 'مسجد مهدم جزئي أو بحاجة إلى صيانة أو فرش وتأثيث',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'structural_condition',
        labelAr:
            'أعمال إنشائية (هبكل خرسانة, رقبة, أساسات, بلاطة سقف, جوائز, صب نطافة, رافعة معدنية, خزانات بيتونية تحت الأرض)',
        type: FieldType.dropdown,
        options: ['سليم', 'بحاجة إلى ترميم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'structural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'structural_condition',
        dependsOnEquals: 'بحاجة إلى ترميم',
      ),
      FormFieldSpec(
        id: 'architectural_condition',
        labelAr:
            'أعمال معمارية وديكور (بلوك, لياسة, عزل, أرضيات, أبواب, شبابيك, تلبيس الحجر, دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'architectural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'architectural_condition',
        dependsOnEquals: 'غير سليم',
      ),
      // FormFieldSpec(
      //   id: 'decor_presence',
      //   labelAr: 'أعمال الديكور (دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
      //   type: FieldType.dropdown,
      //   options: ['موجود', 'غير موجود'],
      //   dependsOn: 'needs_renovation',
      //   dependsOnEquals: true,
      // ),
      // FormFieldSpec(
      //   id: 'decor_missing_percent',
      //   labelAr: 'النسبة المئوية',
      //   type: FieldType.number,
      //   dependsOn: 'decor_presence',
      //   dependsOnEquals: 'غير موجود',
      // ),
      FormFieldSpec(
        id: 'hvac_presence',
        labelAr: 'تكييف وتدفئة ومراوح (خزان مازوت ومولدة)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_presence',
        labelAr:
            'الكهرباء والتيار الخفيف (إنارة, صوت, كاميرات إنذار حريق, قواطع)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'electric_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'renewable_presence',
        labelAr: 'الطاقة البديلة (ألواح, بطاريات ليثيوم, إنفرتر)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'renewable_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'renewable_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'minaret_condition',
        labelAr: 'المئذنة',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'minaret_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'minaret_condition',
        dependsOnEquals: 'غير سليم',
      ),
      FormFieldSpec(
        id: 'water_condition',
        labelAr:
            'العوامل المائية (موضأ, حمامات, تصريف مطري, سقاية الحديقة, خزانات مياه ومضخات)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'water_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'water_condition',
        dependsOnEquals: 'غير سليم',
      ),
    ],
  );

  static const medium = FormSchema(
    typeId: 'medium',
    fields: [
      FormFieldSpec(
        id: 'mosque_name',
        labelAr: 'اسم المسجد',
        type: FieldType.text,
      ),
      FormFieldSpec(
        id: 'area',
        labelAr: 'المساحة بالمتر المربع',
        type: FieldType.number,
        min: 500,
        max: 1100,
      ),
      FormFieldSpec(
        id: 'sharia_institute',
        labelAr: 'معهد شرعي',
        type: FieldType.dropdown,
        options: ['0', '8', '16', '24'],
      ),
      FormFieldSpec(id: 'basement', labelAr: 'قبو', type: FieldType.boolean),
      FormFieldSpec(
        id: 'basement_area',
        labelAr: 'مساحة القبو',
        type: FieldType.number,
        min: 1,
        dependsOn: 'basement',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'imam_house',
        labelAr: 'بيت إمام',
        type: FieldType.dropdown,
        options: ['1', '2', '3'],
      ),
      FormFieldSpec(id: 'courtyard', labelAr: 'صحن', type: FieldType.boolean),
      FormFieldSpec(
        id: 'courtyard_area',
        labelAr: 'مساحة الصحن',
        type: FieldType.number,
        min: 1,
        dependsOn: 'courtyard',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'shops',
        labelAr: 'محلات تجارية',
        type: FieldType.dropdown,
        options: ['2', '3', '4'],
      ),
      FormFieldSpec(
        id: 'shops_area',
        labelAr: 'مساحة المحل الواحد',
        type: FieldType.number,
        min: 1,
        dependsOn: 'shops',
        dependsOnNotEmpty: true,
      ),
      FormFieldSpec(
        id: 'charity_kitchen',
        labelAr: 'مطبخ خيري',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'charity_kitchen_area',
        labelAr: 'مساحة المطبخ الخيري',
        type: FieldType.number,
        min: 1,
        dependsOn: 'charity_kitchen',
        dependsOnEquals: true,
      ),
      FormFieldSpec(id: 'clinic', labelAr: 'عيادة', type: FieldType.boolean),
      FormFieldSpec(
        id: 'clinic_area',
        labelAr: 'مساحة العيادة',
        type: FieldType.number,
        min: 1,
        dependsOn: 'clinic',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'library',
        labelAr: 'مكتبة عامة ورقمية',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'library_area',
        labelAr: 'مساحة المكتبة',
        type: FieldType.number,
        min: 1,
        dependsOn: 'library',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'location',
        labelAr: 'المكان',
        type: FieldType.dropdown,
        options: ['محافظة', 'مدينة', 'بلدة', 'قرية'],
      ),
      FormFieldSpec(
        id: 'quality',
        labelAr: 'الجودة',
        type: FieldType.dropdown,
        options: ['اقتصادي', 'متوسطة', 'عالية'],
      ),
      FormFieldSpec(
        id: 'needs_renovation',
        labelAr: 'مسجد مهدم جزئي أو بحاجة إلى صيانة أو فرش وتأثيث',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'structural_condition',
        labelAr:
            'أعمال إنشائية (هبكل خرسانة, رقبة, أساسات, بلاطة سقف, جوائز, صب نطافة, رافعة معدنية, خزانات بيتونية تحت الأرض)',
        type: FieldType.dropdown,
        options: ['سليم', 'بحاجة إلى ترميم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'structural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'structural_condition',
        dependsOnEquals: 'بحاجة إلى ترميم',
      ),
      FormFieldSpec(
        id: 'architectural_condition',
        labelAr:
            'أعمال معمارية وديكور (بلوك, لياسة, عزل, أرضيات, أبواب, شبابيك, تلبيس الحجر, دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'architectural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'architectural_condition',
        dependsOnEquals: 'غير سليم',
      ),
      // FormFieldSpec(
      //   id: 'decor_presence',
      //   labelAr: 'أعمال الديكور (دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
      //   type: FieldType.dropdown,
      //   options: ['موجود', 'غير موجود'],
      //   dependsOn: 'needs_renovation',
      //   dependsOnEquals: true,
      // ),
      // FormFieldSpec(
      //   id: 'decor_missing_percent',
      //   labelAr: 'النسبة المئوية',
      //   type: FieldType.number,
      //   dependsOn: 'decor_presence',
      //   dependsOnEquals: 'غير موجود',
      // ),
      FormFieldSpec(
        id: 'hvac_presence',
        labelAr: 'تكييف وتدفئة ومراوح (خزان مازوت ومولدة)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_presence',
        labelAr:
            'الكهرباء والتيار الخفيف (إنارة, صوت, كاميرات إنذار حريق, قواطع)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'electric_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'renewable_presence',
        labelAr: 'الطاقة البديلة (ألواح, بطاريات ليثيوم, إنفرتر)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'renewable_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'renewable_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'minaret_condition',
        labelAr: 'المئذنة',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'minaret_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'minaret_condition',
        dependsOnEquals: 'غير سليم',
      ),
      FormFieldSpec(
        id: 'water_condition',
        labelAr:
            'العوامل المائية (موضأ, حمامات, تصريف مطري, سقاية الحديقة, خزانات مياه ومضخات)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'water_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'water_condition',
        dependsOnEquals: 'غير سليم',
      ),
    ],
  );

  static const large = FormSchema(
    typeId: 'large',
    fields: [
      FormFieldSpec(
        id: 'mosque_name',
        labelAr: 'اسم المسجد',
        type: FieldType.text,
      ),
      FormFieldSpec(
        id: 'area',
        labelAr: 'المساحة بالمتر المربع',
        type: FieldType.number,
        min: 1100,
        max: 6000,
      ),
      FormFieldSpec(
        id: 'sharia_institute',
        labelAr: 'معهد شرعي',
        type: FieldType.dropdown,
        options: ['0', '8', '16', '24'],
      ),
      FormFieldSpec(id: 'basement', labelAr: 'قبو', type: FieldType.boolean),
      FormFieldSpec(
        id: 'basement_area',
        labelAr: 'مساحة القبو',
        type: FieldType.number,
        min: 1,
        dependsOn: 'basement',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'imam_house',
        labelAr: 'بيت إمام',
        type: FieldType.dropdown,
        options: ['1', '2', '3'],
      ),
      FormFieldSpec(id: 'courtyard', labelAr: 'صحن', type: FieldType.boolean),
      FormFieldSpec(
        id: 'courtyard_area',
        labelAr: 'مساحة الصحن',
        type: FieldType.number,
        min: 1,
        dependsOn: 'courtyard',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'shops',
        labelAr: 'محلات تجارية',
        type: FieldType.dropdown,
        options: ['2', '3', '4'],
      ),
      FormFieldSpec(
        id: 'shops_area',
        labelAr: 'مساحة المحل الواحد',
        type: FieldType.number,
        min: 1,
        dependsOn: 'shops',
        dependsOnNotEmpty: true,
      ),
      FormFieldSpec(
        id: 'charity_kitchen',
        labelAr: 'مطبخ خيري',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'charity_kitchen_area',
        labelAr: 'مساحة المطبخ الخيري',
        type: FieldType.number,
        min: 1,
        dependsOn: 'charity_kitchen',
        dependsOnEquals: true,
      ),
      FormFieldSpec(id: 'clinic', labelAr: 'عيادة', type: FieldType.boolean),
      FormFieldSpec(
        id: 'clinic_area',
        labelAr: 'مساحة العيادة',
        type: FieldType.number,
        min: 1,
        dependsOn: 'clinic',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'library',
        labelAr: 'مكتبة عامة ورقمية',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'library_area',
        labelAr: 'مساحة المكتبة',
        type: FieldType.number,
        min: 1,
        dependsOn: 'library',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'location',
        labelAr: 'المكان',
        type: FieldType.dropdown,
        options: ['محافظة', 'مدينة', 'بلدة', 'قرية'],
      ),
      FormFieldSpec(
        id: 'quality',
        labelAr: 'الجودة',
        type: FieldType.dropdown,
        options: ['اقتصادي', 'متوسطة', 'عالية'],
      ),
      FormFieldSpec(
        id: 'needs_renovation',
        labelAr: 'مسجد مهدم جزئي أو بحاجة إلى صيانة أو فرش وتأثيث',
        type: FieldType.boolean,
      ),
      FormFieldSpec(
        id: 'structural_condition',
        labelAr:
            'أعمال إنشائية (هبكل خرسانة, رقبة, أساسات, بلاطة سقف, جوائز, صب نطافة, رافعة معدنية, خزانات بيتونية تحت الأرض)',
        type: FieldType.dropdown,
        options: ['سليم', 'بحاجة إلى ترميم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'structural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'structural_condition',
        dependsOnEquals: 'بحاجة إلى ترميم',
      ),
      FormFieldSpec(
        id: 'architectural_condition',
        labelAr:
            'أعمال معمارية وديكور (بلوك, لياسة, عزل, أرضيات, أبواب, شبابيك, تلبيس الحجر, دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'architectural_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'architectural_condition',
        dependsOnEquals: 'غير سليم',
      ),
      // FormFieldSpec(
      //   id: 'decor_presence',
      //   labelAr: 'أعمال الديكور (دهان, محراب, ممبر, سجاد, زخارف, ديكورات حديثة, خزن مصاحف ومكتبة\n خزن أحذية, كراسي, ثريات, طاولات مصاحف, عوامل مائية وحديقة)',
      //   type: FieldType.dropdown,
      //   options: ['موجود', 'غير موجود'],
      //   dependsOn: 'needs_renovation',
      //   dependsOnEquals: true,
      // ),
      // FormFieldSpec(
      //   id: 'decor_missing_percent',
      //   labelAr: 'النسبة المئوية',
      //   type: FieldType.number,
      //   dependsOn: 'decor_presence',
      //   dependsOnEquals: 'غير موجود',
      // ),
      FormFieldSpec(
        id: 'hvac_presence',
        labelAr: 'تكييف وتدفئة ومراوح (خزان مازوت ومولدة)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_presence',
        labelAr:
            'الكهرباء والتيار الخفيف (إنارة, صوت, كاميرات إنذار حريق, قواطع)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'electric_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'electric_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'renewable_presence',
        labelAr: 'الطاقة البديلة (ألواح, بطاريات ليثيوم, إنفرتر)',
        type: FieldType.dropdown,
        options: ['موجود', 'غير موجود'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'renewable_missing_percent',
        labelAr: 'النسبة المئوية',
        type: FieldType.number,
        dependsOn: 'renewable_presence',
        dependsOnEquals: 'غير موجود',
      ),
      FormFieldSpec(
        id: 'minaret_condition',
        labelAr: 'المئذنة',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'minaret_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'minaret_condition',
        dependsOnEquals: 'غير سليم',
      ),
      FormFieldSpec(
        id: 'water_condition',
        labelAr:
            'العوامل المائية (موضأ, حمامات, تصريف مطري, سقاية الحديقة, خزانات مياه ومضخات)',
        type: FieldType.dropdown,
        options: ['سليم', 'غير سليم'],
        dependsOn: 'needs_renovation',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'water_damage_percent',
        labelAr: 'نسبة الضرر المئوية',
        type: FieldType.number,
        dependsOn: 'water_condition',
        dependsOnEquals: 'غير سليم',
      ),
    ],
  );

  static const expansion = FormSchema(
    typeId: 'expansion',
    fields: [
      FormFieldSpec(
        id: 'mosque_name',
        labelAr: 'اسم المسجد',
        type: FieldType.text,
      ),
      FormFieldSpec(
        id: 'sharia_institute',
        labelAr: 'معهد شرعي',
        type: FieldType.dropdown,
        options: ['0', '8', '16', '24'],
      ),
      FormFieldSpec(
        id: 'imam_house',
        labelAr: 'بيت إمام',
        type: FieldType.dropdown,
        options: ['1', '2', '3'],
      ),
      FormFieldSpec(id: 'courtyard', labelAr: 'صحن', type: FieldType.boolean),
      FormFieldSpec(
        id: 'courtyard_area',
        labelAr: 'مساحة الصحن',
        type: FieldType.number,
        min: 1,
        dependsOn: 'courtyard',
        dependsOnEquals: true,
      ),
      FormFieldSpec(
        id: 'shops',
        labelAr: 'محلات تجارية',
        type: FieldType.dropdown,
        options: ['0', '2', '3', '4'],
      ),
      FormFieldSpec(
        id: 'shops_area',
        labelAr: 'مساحة المحل الواحد',
        type: FieldType.number,
        min: 1,
        dependsOn: 'shops',
        dependsOnNotEmpty: true,
      ),
      FormFieldSpec(
        id: 'location',
        labelAr: 'المكان',
        type: FieldType.dropdown,
        options: ['محافظة', 'مدينة', 'بلدة', 'قرية'],
      ),
      FormFieldSpec(
        id: 'quality',
        labelAr: 'الجودة',
        type: FieldType.dropdown,
        options: ['اقتصادي', 'متوسطة', 'عالية'],
      ),
    ],
  );

  static const all = [musalla, small, medium, large, expansion];
}
